server:
  port: 9090
  servlet:
    context-path: /
logging:
  file:
    name: logs/server.log
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://192.168.100.102:3307/maven?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: natasha
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.cn.nts.nts13.root.entity
  mapper-locations: classpath:mapper/*.xml