server:
  port: 9090
  servlet:
    context-path: /boot
logging:
  file:
    name: logs/server.log
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html